spring:
  application:
    name: webclient
  config:
    import: configserver:${SPRING_CONFIG_URI:http://localhost:8888/}
  cloud:
    config:
      label: latest
      name: webclient
      profile: dev
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/